### ISSUE TITLE
Unable to locate element: [name="VIDEO_MADE_FOR_KIDS_NOT_MFK"]

### ISSUE THREAD

**Issue by Sakimotor** [7x11x13/songs-to-youtube#12]
Log : 
```
[15:04:44] [ERROR] Traceback (most recent call last):
  File "youtube_uploader_selenium\__init__.py", line 125, in upload_all
  File "youtube_uploader_selenium\__init__.py", line 152, in upload
  File "youtube_uploader_selenium\__init__.py", line 364, in __upload
  File "youtube_uploader_selenium\__init__.py", line 226, in __find
  File "selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [name="VIDEO_MADE_FOR_KIDS_NOT_MFK"]
```

![2021-08-13_150445](https://user-images.githubusercontent.com/20578016/129362915-d4e2e2e5-79ca-4dcc-90cd-b922f869e705.png)

The video is already rendered and partly uploaded.

**Comment by Sakimotor** [comment]
Fixed with latest release.
