### ISSUE TITLE
Cannot upload any videos, possibly due to 2-step verification on google account connected to yt?

### ISSUE THREAD

**Issue by xoark** [7x11x13/songs-to-youtube#13]
I keep getting this error:
Also, it triggers Google to send me emails/alerts about "suspicious activity detected" and signs me out. Could this be because I am using two-step verification on this account?
<img width="518" alt="Screenshot 2021-08-21 030133" src="https://user-images.githubusercontent.com/88959307/130315151-c866dc70-5a8e-4ec9-a53b-4c61ad2d8c94.png">
<img width="418" alt="Screenshot 2021-08-21 030209" src="https://user-images.githubusercontent.com/88959307/130315174-87a1b9fc-223d-40bf-a725-2c2154b66f59.png">

`[02:55:14] [ERROR] Traceback (most recent call last):
  File "youtube_uploader_selenium\__init__.py", line 125, in upload_all
  File "youtube_uploader_selenium\__init__.py", line 152, in upload
  File "youtube_uploader_selenium\__init__.py", line 242, in __upload
  File "youtube_uploader_selenium\__init__.py", line 226, in __find
  File "selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //input[@type='file']
[02:55:14] [ERROR] Screenshot saved to C:/Users/enort/AppData/Roaming/7x11x13/songs-to-youtube\screenshots\2021-08-21_025514.png`

**Comment by xoark** [comment]
Attempting to turn off 2-step verification seems to not fix the issue.

**Comment by xoark** [comment]
Issue fixed by turning back on 2-step verification, then exporting the cookie JSON into the file and replacing the old JSON w/ the new one :)
