### ISSUE TITLE
Exception: Could not find INPUT_FILE_VIDEO

### ISSUE THREAD

**Issue by viatekh** [7x11x13/songs-to-youtube#24]
```
09:14:16] [ERROR] Traceback (most recent call last):
  File "/Users/tekh/Downloads/songs-to-youtube-master/src/youtube_uploader_selenium/__init__.py", line 159, in upload_all
    success = self.upload(file, job)
  File "/Users/tekh/Downloads/songs-to-youtube-master/src/youtube_uploader_selenium/__init__.py", line 190, in upload
    return self.__upload(video_path, metadata)
  File "/Users/tekh/Downloads/songs-to-youtube-master/src/youtube_uploader_selenium/__init__.py", line 287, in __upload
    self.__find(By.XPATH, Constant.INPUT_FILE_VIDEO).send_keys(absolute_video_path)
  File "/Users/tekh/Downloads/songs-to-youtube-master/src/youtube_uploader_selenium/__init__.py", line 275, in __find
    raise Exception(f"Could not find {Constant.lookup(constant)}")
Exception: Could not find INPUT_FILE_VIDEO

```
![2022-03-01_091416](https://user-images.githubusercontent.com/56348559/156140604-1255c616-5243-4b38-b846-b67593799634.png)

personally i find the "could not find video" message is at odds with the generated screenshot, which is pertaining to logging in.

**Comment by Sakimotor** [comment]
Try generating a new json file for your cookies, that fixed the issue on my side.
