### ISSUE TITLE
Tagging not working properly

### ISSUE THREAD

**Issue by Sakimotor** [7x11x13/songs-to-youtube#25]
[20:47:07] [INFO] Setting extra options
[20:47:14] [ERROR] Traceback (most recent call last):
  File "youtube_uploader_selenium\__init__.py", line 159, in upload_all
  File "youtube_uploader_selenium\__init__.py", line 200, in upload
  File "youtube_uploader_selenium\__init__.py", line 430, in __upload
  File "youtube_uploader_selenium\__init__.py", line 285, in __find
Exception: Could not find TAGS_TEXT_INPUT

![2022-03-20_173117](https://user-images.githubusercontent.com/20578016/159784077-c060fa62-9fcd-45af-b7ce-1bbe5fabdf8e.png)

idk why but tagging simply doesn't seem to work anymore, the scripts presses the "plus" buttons where the tagging options are hidden, but doesn't find the field itself.

**Comment by vdqzd** [comment]
tags stopped working for me a little before you posted this and now not even things like description or not for kids label works, so a jerryrig fix i did was disabled hide browser so i could go and edit stuff myself and publish the video not sure of any real way to get anything to work

**Comment by 7x11x13** [comment]
Should be fixed in v0.11.20, thanks to @That-Thing
