### ISSUE TITLE
Code not Run

### ISSUE THREAD

**Issue by ankitsiliconithub** [7x11x13/songs-to-youtube#3]
This kind of error display

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from song_settings_widget import SongSettingsWidget
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shiboken6/files.dir/shibokensupport/__feature__.py", line 140, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/ankitpatel/Desktop/StatusVideo/songs-to-youtube-2b7fb81da2b65bf42af37e62b5805f0e1ee66eca/song_settings_widget.py", line 6, in <module>
    from settings import SETTINGS_VALUES, SettingCheckBox, CoverArtDisplay, SettingsScrollArea
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shiboken6/files.dir/shibokensupport/__feature__.py", line 140, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/ankitpatel/Desktop/StatusVideo/songs-to-youtube-2b7fb81da2b65bf42af37e62b5805f0e1ee66eca/settings.py", line 100
    if (path := get_image_from_mimedata(event.mimeData())) is not None:
             ^
SyntaxError: invalid syntax

**Comment by 7x11x13** [comment]
Python version >= 3.8 is required, I should add that to the readme
