### ISSUE TITLE
Cannot run: No module named 'blinker._saferef'

### ISSUE THREAD

**Issue by justjakka** [7x11x13/songs-to-youtube#58]
Cannot run the script directly from source, installed through PyPI or from the binary. The error remains the same:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jakka/scripts/songs-to-youtube/songs_to_youtube/main.py", line 19, in <module>
    from songs_to_youtube.song_tree_widget import SongTreeWidget
  File "/home/jakka/scripts/songs-to-youtube/songs_to_youtube/song_tree_widget.py", line 12, in <module>
    from songs_to_youtube.upload import Uploader
  File "/home/jakka/scripts/songs-to-youtube/songs_to_youtube/upload.py", line 10, in <module>
    from youtube_up import Metadata as YTMetadata
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/youtube_up/__init__.py", line 125, in <module>
    from .uploader import *
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/youtube_up/uploader.py", line 17, in <module>
    from seleniumwire import webdriver
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/seleniumwire/webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/seleniumwire/backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/seleniumwire/server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/seleniumwire/handler.py", line 5, in <module>
    from seleniumwire import har
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/seleniumwire/har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 15, in <module>
    import seleniumwire.thirdparty.mitmproxy.options
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/options.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import optmanager
  File "/home/jakka/scripts/songs-to-youtube/.venv/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/optmanager.py", line 9, in <module>
    import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef'
```

The issue is mentioned [here](https://www.marekrost.cz/selenium-wire-how-to-resolve-blinker-saferef). Proposing adding direct blinker dependency.

**Comment by 7x11x13** [comment]
Could you try using python 3.11 instead of 3.12? I think that might be a quick fix while I look into it fixing the issue (I'm busy for the next week or so)

**Comment by meow6969** [comment]
`pip install blinker==1.7` will fix it

**Comment by uniwuni** [comment]
> `pip install blinker==1.7` will fix it

Doesn't work for me, neither on 3.11 nor 3.12

**Comment by 7x11x13** [comment]
Try v0.12.15, it should be fixed now
