### ISSUE TITLE
How do i fix this bug?

### ISSUE THREAD

**Issue by zettaexa** [7x11x13/songs-to-youtube#63]
Not sure what I've done, it worked well before but now I'm just confused

```
[14:55:49] [ERROR] Traceback (most recent call last):
  File "upload.py", line 160, in run
  File "youtube_up\uploader.py", line 170, in upload
youtube_up.uploader.YTUploaderException: Could not create video
[14:55:49] [ERROR] C:/Users/user/Downloads/young beidnahga/01 - continuous smooth jazz trepanation.mp3.mkv - Error while uploading
```

**Comment by zettaexa** [comment]
Nevermind it was the daily upload limit YT put out for my channel
