### ISSUE TITLE
Unable to upload to an alternate channel

### ISSUE THREAD

**Issue by hocermanc** [7x11x13/songs-to-youtube#7]
Was able to upload to my channel, but would get a cookie error after i restarted my computer. I fixed this by downloading cookies again in a browser window with nothing but youtube after i logged in. However, if I try to do the same for a different channel which is registered under the same email/password login, it always fails. error is as follows

```
[00:02:01] [ERROR] Traceback (most recent call last):
  File "youtube_uploader_selenium\__init__.py", line 118, in upload_all
  File "youtube_uploader_selenium\__init__.py", line 132, in upload
  File "youtube_uploader_selenium\__init__.py", line 161, in __login
  File "selenium\webdriver\remote\webdriver.py", line 894, in add_cookie
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.InvalidCookieDomainException: Message: Cookies may only be set for the current domain (accounts.google.com)
```

Additionally, the few times I was able to get it to work today, selenium would not click the 'sign in' button and I had to do it manually. Is any of this something on my end?

**Comment by 7x11x13** [comment]
Are you using the latest version? (v0.9.0)

**Comment by 7x11x13** [comment]
You should never have to click on the sign in button at all, it should just reload youtube.com and login with the cookies. Sometimes it takes a while (~10 seconds). If it reloads and takes you to the sign-in page at accounts.google.com then something is wrong. I'll see if I can reproduce with my own account to troubleshoot.

**Comment by 7x11x13** [comment]
See if v0.9.1 fixes this for you

**Comment by hocermanc** [comment]
Thanks, it worked on the alt channel now, but now switching back to the main channel gives this error

```
[14:44:30] [ERROR] Traceback (most recent call last):
  File "youtube_uploader_selenium\__init__.py", line 118, in upload_all
  File "youtube_uploader_selenium\__init__.py", line 137, in upload
  File "youtube_uploader_selenium\__init__.py", line 227, in __upload
  File "youtube_uploader_selenium\__init__.py", line 211, in __find
  File "selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //input[@type='file']
```

**Comment by 7x11x13** [comment]
What happens in the browser? Does it load the upload video page?

**Comment by hocermanc** [comment]
It opens youtube, reloads the page, and then attempts to sign in but doesn't input any text. Window closes

**Comment by 7x11x13** [comment]
It shouldn't ever go to a login page, it should just reload youtube.com and you will be logged in. Maybe the cookies for your original account have expired now? I can't reproduce on my end.

**Comment by hocermanc** [comment]
Redownloaded cookies, this time it worked both on the main and alt accounts without having to reopen the program.
On an unrelated note, it seems using a gif as the cover image for a song crashes the program, but I have not tried reproducing this
